pretrained_path: "pretrained/VoxCPM-1.5-VN"
train_manifest: "/kaggle/input/datasets/nguyendangtri1702/dataset/filtered_dataset/train.jsonl"
val_manifest: ""

sample_rate: 44100
# --- TỐI ƯU HÓA CHO KAGGLE 16GB VRAM T4 x2 ---
batch_size: 4                
grad_accum_steps: 2         
max_batch_tokens: 4096       
# --------------------------------

num_workers: 4               
num_iters: 800               # Mức chuẩn cho 117 chunks (Tương đương ~110 epochs)
max_steps: 800
log_interval: 10
valid_interval: 200          # Cứ 200 bước kiểm tra 1 lần
save_interval: 200           # Lưu model mỗi 200 bước

learning_rate: 0.0001
weight_decay: 0.01
warmup_steps: 40

# Lưu thẳng model và log vào thư mục working của Kaggle
save_path: "/kaggle/working/voxcpm/checkpoints"
tensorboard: "/kaggle/working/voxcpm/logs"

lambdas:
  loss/diff: 1.0
  loss/stop: 1.0

# LoRA configuration
lora:
  enable_lm: true
  enable_dit: true
  enable_proj: false

  r: 16                  # Giảm Rank từ 32 xuống 16: Vẫn dư sức clone giọng 1 người, lại tiết kiệm VRAM đáng kể
  alpha: 16              # Scale = alpha/r = 1.0 (Giữ model ổn định)
  dropout: 0.05          # Bật nhẹ 5% dropout để chống học vẹt (overfitting) do data 8 phút khá mỏng

  # Target modules (Giữ nguyên theo chuẩn của VoxCPM)
  target_modules_lm: ["q_proj", "v_proj", "k_proj", "o_proj"]
  target_modules_dit: ["q_proj", "v_proj", "k_proj", "o_proj"]

dtype: float16 # Đổi sang float16 để tăng tốc x2 và tiết kiệm VRAM trên card T4